### ISSUE TITLE
Error - clusterPlots

### ISSUE THREAD

**Issue by ndoyle-1** [g-tierney/stLDA-C_public#2]
I've tried running the demo code but encounter the following errors - is there a fix?

Error in results_array_mean(.) : 
  could not find function "results_array_mean"

Error in arrangeGrob(...) : object 'clusterPlots' not found

Many thanks in advance.

**Comment by g-tierney** [comment]
I just re-cloned the repo and the code works on my computer. Did you source the helper_functions.R file? That is where the results_array_mean function is defined.

**Comment by ndoyle-1** [comment]
Thanks - got it working. My machine added html to the scripts, so I re-copied those.

**Comment by ndoyle-1** [comment]
How do I read from a saved CSV or a data frame instead of using the example data?

**Comment by ndoyle-1** [comment]
Figured it out - thanks for getting me started.

**Comment by g-tierney** [comment]
Great! Happy to help.
